# Generated by Django 5.2.6 on 2025-09-20 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('path', models.TextField()),
                ('hidden', models.BooleanField(default=False)),
                ('sync', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.TextField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('poster', models.TextField(blank=True, null=True)),
                ('is_video', models.BooleanField(default=False)),
                ('ext', models.CharField(max_length=10)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mediahub.library')),
            ],
        ),
    ]
