# Generated by Django 5.2.6 on 2025-09-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='type',
            field=models.CharField(choices=[('movies', 'Movies'), ('pictures', 'Pictures'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
