# Generated by Django 5.2.6 on 2025-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0003_folderitem_mediaitem_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
