# Generated by Django 5.2.6 on 2025-09-21 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0004_mediaitem_height_mediaitem_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediahub.mediaitem')),
            ],
        ),
    ]
