# Generated by Django 5.2.6 on 2025-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0005_playbackprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='backdrop',
            field=models.TextField(blank=True, null=True),
        ),
    ]
