# Generated by Django 5.2.6 on 2025-09-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0006_mediaitem_backdrop'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
