# Generated by Django 5.2.6 on 2025-09-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0007_mediaitem_description_mediaitem_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='genre',
            field=models.JSONField(default=list),
        ),
    ]
