# Generated by Django 5.2.6 on 2025-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0008_mediaitem_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
