# Generated by Django 5.2.6 on 2025-09-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0009_mediaitem_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
