# Generated by Django 5.2.6 on 2025-09-27 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0010_mediaitem_tmdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubtitleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(unique=True)),
                ('number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mediahub.language')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='mediahub.mediaitem')),
            ],
            options={
                'unique_together': {('media_item', 'lang', 'number')},
            },
        ),
    ]
